version: 1.0.{build}
os: Visual Studio 2015
environment:
  matrix:
    - ARCH: amd64
    - ARCH: x86

clone_folder: c:\dev\TDengine
clone_depth: 1

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%

before_build:
  - cd c:\dev\TDengine
  - md build

build_script:
  - cd build
  - cmake -G "NMake Makefiles" ..
  - nmake install
  
notifications:
- provider: Email
  to:
  - sangshuduo@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
