global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
     - targets: ["localhost:9090"]
  - job_name: "taoskeeper"
    static_configs:
      - targets: ["taoskeeper:6043"]
  - job_name: "node"
    static_configs:
      - targets: ["nodeexporter:9100"]
