[package]
name = "xnoded"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48", features = ["full"] }
anyhow = "1.0"
axum = "0.8.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
clap = { version = "4.5.30", features = ["default", "derive"] }
clap-verbosity-flag = { version = "3.0.2" }
log = "0.4"
env_logger = "0.11.8"