# validate test cases on PRs. The workflow runs a validation script for each changed file.

name: Validate Test Cases

on:
  push:
    branches:
      - 'new_test_framework'
    paths:
      - 'test/cases/**/*.py'
  pull_request:
    branches:
      - 'main'
      - '3.0'
    paths:
      - 'test/cases/**/*.py'

jobs:
  validate_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Get all changed case files
        id: changed-case-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            test/cases/**/*.py

      - name: Validate test files
        if: steps.changed-case-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-case-files.outputs.all_changed_files }}
        run: |
          EXIT_CODE=0
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
            python .github/scripts/validate_tests.py "$file" || EXIT_CODE=1
          done
          exit $EXIT_CODE
